// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819105356_ReInitial")]
    partial class ReInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Restaurant.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1404/1404945.png",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046784.png",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 3,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046786.png",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046795.png",
                            Name = "Salads"
                        },
                        new
                        {
                            Id = 5,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1404/1404948.png",
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 6,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046803.png",
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 7,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046790.png",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 8,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046841.png",
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 9,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1046/1046779.png",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 10,
                            IconUrl = "https://cdn-icons-png.flaticon.com/512/1404/1404942.png",
                            Name = "Burgers"
                        });
                });

            modelBuilder.Entity("Restaurant.Data.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Percentage = 5,
                            StartDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Restaurant.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Restaurant.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Classic tomato, mozzarella, and basil pizza.",
                            ImageUrl = "https://source.unsplash.com/600x400/?margherita,pizza",
                            IsAvailable = true,
                            Name = "Margherita",
                            Price = 49.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Sweet pizza topped with Nutella and fruits.",
                            ImageUrl = "https://source.unsplash.com/600x400/?nutella,dessert",
                            IsAvailable = true,
                            Name = "Nutella Pizza",
                            Price = 59.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "330ml cold soft drink.",
                            ImageUrl = "https://source.unsplash.com/600x400/?coca-cola,drink",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 9.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Chicken, croutons, and parmesan.",
                            ImageUrl = "https://source.unsplash.com/600x400/?caesar,salad",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 38.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Spicy tomato pasta.",
                            ImageUrl = "https://source.unsplash.com/600x400/?penne,pasta",
                            IsAvailable = true,
                            Name = "Penne Arrabbiata",
                            Price = 42.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Traditional Turkish red lentil soup.",
                            ImageUrl = "https://source.unsplash.com/600x400/?lentil,soup",
                            IsAvailable = true,
                            Name = "Lentil Soup",
                            Price = 19.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Deep-fried mozzarella cheese.",
                            ImageUrl = "https://source.unsplash.com/600x400/?mozzarella,snacks",
                            IsAvailable = true,
                            Name = "Mozzarella Sticks",
                            Price = 27.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Oven-roasted seasonal vegetables.",
                            ImageUrl = "https://source.unsplash.com/600x400/?vegetable,meal",
                            IsAvailable = true,
                            Name = "Vegetable Casserole",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "Traditional Turkish breakfast assortment.",
                            ImageUrl = "https://source.unsplash.com/600x400/?breakfast,food",
                            IsAvailable = true,
                            Name = "Breakfast Platter",
                            Price = 69.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "Beef patty with cheddar cheese.",
                            ImageUrl = "https://source.unsplash.com/600x400/?cheeseburger",
                            IsAvailable = true,
                            Name = "Cheeseburger",
                            Price = 48.00m
                        });
                });

            modelBuilder.Entity("Restaurant.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "John Smith",
                            GuestCount = 2,
                            Notes = "Window seat",
                            PhoneNumber = "5551234567",
                            ReservationDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Emily Johnson",
                            GuestCount = 4,
                            Notes = "",
                            PhoneNumber = "5552345678",
                            ReservationDate = new DateTime(2025, 8, 19, 18, 0, 0, 0, DateTimeKind.Local),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Michael Lee",
                            GuestCount = 3,
                            Notes = "Birthday celebration",
                            PhoneNumber = "5553456789",
                            ReservationDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Sophia Davis",
                            GuestCount = 5,
                            Notes = "",
                            PhoneNumber = "5554567890",
                            ReservationDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "David Brown",
                            GuestCount = 2,
                            Notes = "Romantic table",
                            PhoneNumber = "5555678901",
                            ReservationDate = new DateTime(2025, 8, 19, 21, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CustomerName = "Olivia Wilson",
                            GuestCount = 6,
                            Notes = "",
                            PhoneNumber = "5556789012",
                            ReservationDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            CustomerName = "James Miller",
                            GuestCount = 3,
                            Notes = "Non-smoking area",
                            PhoneNumber = "5557890123",
                            ReservationDate = new DateTime(2025, 8, 19, 19, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CustomerName = "Ava Martinez",
                            GuestCount = 1,
                            Notes = "",
                            PhoneNumber = "5558901234",
                            ReservationDate = new DateTime(2025, 8, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CustomerName = "William Anderson",
                            GuestCount = 2,
                            Notes = "",
                            PhoneNumber = "5559012345",
                            ReservationDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CustomerName = "Emma Thomas",
                            GuestCount = 4,
                            Notes = "Birthday dinner",
                            PhoneNumber = "5550123456",
                            ReservationDate = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Restaurant.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Amazing flavor!",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8304),
                            CustomerName = "John",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great taste but a bit salty.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8308),
                            CustomerName = "Emily",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Average meal.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8311),
                            CustomerName = "Michael",
                            Rating = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Absolutely loved it!",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8314),
                            CustomerName = "Sophia",
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Not what I expected.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8317),
                            CustomerName = "David",
                            Rating = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Tasty and well presented.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8319),
                            CustomerName = "Olivia",
                            Rating = 4
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Top quality!",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8324),
                            CustomerName = "James",
                            Rating = 5
                        },
                        new
                        {
                            Id = 8,
                            Comment = "It was okay.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8326),
                            CustomerName = "Ava",
                            Rating = 3
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Quick service, nice meal.",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8329),
                            CustomerName = "William",
                            Rating = 4
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Best burger I've had!",
                            CreatedAt = new DateTime(2025, 8, 19, 13, 53, 55, 40, DateTimeKind.Local).AddTicks(8332),
                            CustomerName = "Emma",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Data.Models.Order", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Restaurant.Data.Models.OrderItem", b =>
                {
                    b.HasOne("Restaurant.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Data.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Payment", b =>
                {
                    b.HasOne("Restaurant.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Product", b =>
                {
                    b.HasOne("Restaurant.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.Data.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
